CREATE DATABASE Mobiili;
USE Mobiili;

CREATE TABLE User (
ID_user INT AUTO_INCREMENT PRIMARY KEY,
Firstname TINYTEXT not null,
Lastname TINYTEXT not null,
Username TINYTEXT not null,
Email TINYTEXT not null,
Password TINYTEXT not null);

CREATE TABLE FOOD_RECIPES (
ID_food INT AUTO_INCREMENT PRIMARY KEY,
IMG_URL TINYTEXT,
Description MEDIUMTEXT,
food_name TINYTEXT);

CREATE TABLE DRINK_RECIPES (
ID_drink INT AUTO_INCREMENT PRIMARY KEY,
Drink_name TINYTEXT,
Descripsion MEDIUMTEXT,
IMG_URL TINYTEXT);

CREATE TABLE Link (
ID_user INT,
ID_food INT,
ID_drink INT,
PRIMARY KEY(ID_user,ID_food,ID_drink),
FOREIGN KEY(ID_user)
	REFERENCES User(ID_user)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (ID_food)
	REFERENCES FOOD_RECIPES(ID_food)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (ID_drink)
	REFERENCES DRINK_RECIPES(ID_drink)
	ON DELETE RESTRICT ON UPDATE CASCADE);


INSERT INTO DRINK_RECIPES VALUES (NULL, "Koff", "1. Avaa pullo 
2. juo
3. profit", 'http://www.koff.fi/assets/images/products/Koff-3.png');
