CREATE DATABASE Mobiili;
USE Mobiili;

CREATE TABLE User (
ID_user INT AUTO_INCREMENT PRIMARY KEY,
Firstname VARCHAR(10) not null,
Lastname VARCHAR(10) not null,
Username VARCHAR(10) not null,
Email VARCHAR(20) not null,
Password VARCHAR(15) not null);

CREATE TABLE FOOD_RECIPES (
ID_food INT AUTO_INCREMENT PRIMARY KEY,
IMG_URL VARCHAR(20),
Description TEXT,
food_name VARCHAR(15));

CREATE TABLE DRINK_RECIPES (
ID_drink INT AUTO_INCREMENT PRIMARY KEY,
Drink_name VARCHAR(15),
Descripsion TEXT,
IMG_URL VARCHAR(20));

CREATE TABLE Link (
ID_user INT,
ID_food INT,
ID_drink INT,
PRIMARY KEY(ID_user,ID_food,ID_drink),
FOREIGN KEY(ID_user)
	REFERENCES User(ID_user)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (ID_food)
	REFERENCES FOOD_RECIPES(ID_food)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (ID_drink)
	REFERENCES DRINK_RECIPES(ID_drink)
	ON DELETE RESTRICT ON UPDATE CASCADE);

